# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFROM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 80, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 180, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 270, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 160, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 270, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.plantext_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.plantext_txt.setGeometry(QtCore.QRect(140, 140, 271, 61))
        self.plantext_txt.setObjectName("plantext_txt")
        self.ciphertext_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.ciphertext_txt.setGeometry(QtCore.QRect(130, 240, 271, 61))
        self.ciphertext_txt.setObjectName("ciphertext_txt")
        self.information_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.information_txt.setGeometry(QtCore.QRect(590, 140, 271, 61))
        self.information_txt.setObjectName("information_txt")
        self.signture_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.signture_txt.setGeometry(QtCore.QRect(590, 240, 271, 61))
        self.signture_txt.setObjectName("signture_txt")
        self.genaratekeys_btn = QtWidgets.QPushButton(self.centralwidget)
        self.genaratekeys_btn.setGeometry(QtCore.QRect(590, 80, 81, 23))
        self.genaratekeys_btn.setObjectName("genaratekeys_btn")
        self.encrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt_btn.setGeometry(QtCore.QRect(130, 340, 81, 23))
        self.encrypt_btn.setObjectName("encrypt_btn")
        self.decrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt_btn.setGeometry(QtCore.QRect(320, 340, 81, 23))
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.verify_btn = QtWidgets.QPushButton(self.centralwidget)
        self.verify_btn.setGeometry(QtCore.QRect(780, 340, 81, 23))
        self.verify_btn.setObjectName("verify_btn")
        self.sign_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sign_btn.setGeometry(QtCore.QRect(590, 340, 81, 23))
        self.sign_btn.setObjectName("sign_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plan Text"))
        self.label_3.setText(_translate("MainWindow", "Signture"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Cipher Text"))
        self.genaratekeys_btn.setText(_translate("MainWindow", "Genarate Keys"))
        self.encrypt_btn.setText(_translate("MainWindow", "Encrypt"))
        self.decrypt_btn.setText(_translate("MainWindow", "Decrypt"))
        self.verify_btn.setText(_translate("MainWindow", "Verify"))
        self.sign_btn.setText(_translate("MainWindow", "Sign"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
